## Numpy Array and basics

In [1]:
import numpy as np

### creating array from list



In [ ]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3,4,5], [6,7,8,9, 10]])
# Note that the size of both list should be in 2d array
print(arr_2d)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### List vs Numpy list


In [ ]:
py_list = [1,2,3]
np_arr = np.array(py_list)

# if we multiply numpy list then each item will be multiplied 
# if we multiply normal python list then the list will 2 * initial size
print('numpy list multiplication', np_arr*2)
print('Python list multiplication', py_list*2)

numpy list multiplication [2 4 6]
Python list multiplication [1, 2, 3, 1, 2, 3]


### Checking calculation Speed 


In [ ]:
import time

start = time.time()
python_list = [i*2 for i in range(1000000)]
print("Python List operation time: ", time.time() - start)

start = time.time()
numpy_list = np.arange(1000000) * 2
print("Python List operation time: ", time.time() - start)



### Creating arrays from strach

In [ ]:
zeroes = np.zeros((3, 4))
print("Zeroes matrix: \n", zeroes)
# creating arrays of zeroes or ones with r X c is passes as tuple inside "()"
ones = np.ones((3, 4))
print("Ones matrix: \n", ones)

# or similary we can do that for any number just pass tuple as dimension of 
# matrix and the number we want to fill it with

any_desired_number_full = np.full((5, 5), 5)
print("Filling any desired numbered matrix: \n", any_desired_number_full)

# we can also have random matrix
# np.random is class in itself it have many methods
random_matrices = np.random.random((2, 2))
print("Random Matrix:\n", random_matrices)

# sequence
sequence = np.arange(0, 10, 2)
print("Sequence:\n", sequence)

### Vectors, Matrices, and Tensor


In [ ]:
vector = np.array([1,2,3,4])
print("Vector:\n", vector)

matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
])

print("Matrix:\n", matrix)

tensor = np.array([
    [[1,2], [3,4]],
    [[5,6], [7, 8]]
])
print("Tensor:\n", tensor)
print("Dimension:\n",tensor.ndim)

### Array Properites

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
])

print("Shape: ",arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Data type", arr.dtype)


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Array:\n", arr)

# convert list into matrix
reshaped = arr.reshape((4, 3))
print("Reshaped:\n",reshaped)

# flattens the matrix -> back to array
flattend = reshaped.flatten()
print("Flattened:\n",flattend)

# Returns view instead of copy (Returns original array)
raveled = reshaped.ravel()
print("Raveled:\n",raveled)

# Transpose Of matrix
transpose = reshaped.T;
print("\nTransposed Matrix:\n",transpose)