## Numpy Array Operations

In [2]:
import numpy as np

In [ ]:
arr = np.arange(1, 11)
print(arr)

print("Slicing (till n - 1 index): ", arr[:100]) 
#Note that if n >= len(arr) then it will take till n - 1 index

print("Slicing (Range): ", arr[2:10])
# [startIndex: EndIndex + 1]

print("Negative Slicing: ", arr[-1:])
# [-n: ] negative number start indexing from -1 and from last index

print("Starting From 0 till last -1: ", arr[:-1])
# [-n: ] negative number start indexing from -1 and from last index

print("Another Negative Slicing: ", arr[-4:-1])
# [startIndex: tillIndex - 1] -1 means last index then it will go till lastIndex - 1


#NOTE:The starting index will be in the left of ':' and if not mentioned will be 0 by default
# NOTE: Similar case for right number ":" but till only leftNumber - 1

[ 1  2  3  4  5  6  7  8  9 10]
Slicing (till n - 1 index):  [ 1  2  3  4  5  6  7  8  9 10]
Slicing (Range):  [ 3  4  5  6  7  8  9 10]
Negative Slicing:  [10]
Starting From 0 till last -1:  [1 2 3 4 5 6 7 8 9]
Another Negative Slicing:  [7 8 9]


In [87]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific Element: ", arr_2d[1, 2])
# arr[a, b] means bth element of ath element present in arr_2d

print("Entire Row: ", arr_2d[1])
print("Entire Col: ", arr_2d[:, 2])

Specific Element:  6
Entire Row:  [4 5 6]
Entire Col:  [3 6 9]


### Sorting

In [106]:
unsorted = np.array([1,2,4,1,2,8,10,99,23])

print("Sorted Array: ", np.sort(unsorted))

unsorted_2d_array = np.array([
    [1,5],
    [5, 6],
    [2, 5]
])

print("sorted 2d array\n", np.sort(unsorted_2d_array, axis=0))

Sorted Array:  [ 1  1  2  2  4  8 10 23 99]
sorted 2d array
 [[1 5]
 [2 5]
 [5 6]]


### Filter

In [3]:
number = np.arange(1, 11)

even_number = number[number % 2 == 0]
odd_number = number[number % 2 != 0]

print("Even number: ", even_number)
print("Odd number: ", odd_number)

Even number:  [ 2  4  6  8 10]
Odd number:  [1 3 5 7 9]


### Filter with mask

In [ ]:
# Same As Above, the condition that will be applied is the "mask"
mask = number > 5
print("Numbers greater than 5: ", number[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy Indexing Vs np.where()

In [ ]:
indices = [1, 2, 3]
# index wise
print(number[indices])

where_result = np.where(number >= 7)
print("NP Where: ", number[where_result])

[2 3 4]
NP Where:  [ 7  8  9 10]
[[ 1  2  3  4  5 12 14 16 18 20]]


In [30]:
condition_array = np.where(number >= 6, "true", "false")
# np.where(condition, x, y)
# when condition is true then x is applied and y is applied when false
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing The Data

In [44]:
arr1 = np.array([1, 2, 3, 5])
arr2 = np.array([4, 5, 6, 7])

# combined_array = arr1 + arr2
combined_array = np.concatenate((arr1, arr2))
# using arr1 + arr2 will add the respective elements
# Also NOTE:- arr1 and arr2 should have same length
print("Combined Array: ", combined_array)

Combined Array:  [1 2 3 5 4 5 6 7]


### Compatibility

In [48]:
arr_a = np.array([1,2,3])
arr_b = np.array([5,6,1,8])
arr_c = np.array([9,0,4])

print("Array Compatibility: ", arr_a.shape == arr_b.shape)

Array Compatibility:  False


### Adding Rows and Cols

In [123]:
original = np.array([
    [1, 3],
    [3, 6]
])

new_row = np.array([[4, 7]])

print("Dimesions of New Row: ", np.ndim(new_row))
print("Dimesions of Original: ", np.ndim(original))

with_new_row = np.vstack((new_row, original))

# depending on positon we can add new_row either on top
# or on the bottom of the row

# vstack adds in row
print("Original Matrix: \n",original)
print("With New Row Matrix: \n",with_new_row)

# adding new column
# hstack is used for column
new_col = np.array([[4, 5], [9, 1], [9, 3]])
print("Dimesions of new col" , np.ndim(new_col))
print("Dimesions of With New Row" , np.ndim(with_new_row))

with_new_col = np.hstack((with_new_row, new_col))
print("With New Col Matrix: \n", with_new_col)

#NOTE:
# Just Remember that Vstack mean fill the stack vertically (Either top-down or bottom-up)
# Similary hstack means filling the stack horizontally(Either left-right or right-left)

Dimesions of New Row:  2
Dimesions of Original:  2
Original Matrix: 
 [[1 3]
 [3 6]]
With New Row Matrix: 
 [[4 7]
 [1 3]
 [3 6]]
Dimesions of new col 2
Dimesions of With New Row 2
With New Col Matrix: 
 [[4 7 4 5]
 [1 3 9 1]
 [3 6 9 3]]


### Deletion

In [ ]:
arr = np.array([1,3,5,6])
deleted = np.delete(arr, 2)
# returns np array after deletion

print(arr)

[1 3 5 6]
