### Practice With Real Data

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],   # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],   # Beijing Bites
    [3, 200000, 230000, 260000, 300000],   # Pizza Hub
    [4, 180000, 210000, 240000, 270000],   # Burger Point
    [5, 160000, 185000, 205000, 230000]    # Chai Point
])

print("==== Zomato sales analysis ====")

print("Shape of The data: ",sales_data.shape)
print("Sample data for first three restuarent\n", sales_data[:, 1:])


==== Zomato sales analysis ====
Shape of The data:  (5, 5)
Sample data for first three restuarent
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [48]:
# Total sales per year
# NOTE: For cols we take axis = 0, and for rows we take axis = 1
print(np.sum(sales_data, axis=0))
print("Yearly Total: \n", np.sum(sales_data[:, 1:], axis= 0))

#Minimum Sales per restaurent
min_sales = np.min(sales_data[:, 1:], axis=1)
print("Min Sales Per Restaurents: ", min_sales)

# Maximum Sales per year
max_sales = np.max(sales_data[:, 1:], axis= 0)
print("Max Sales By each Year:\n", max_sales)

# Average Sales per year 
average_sales_year = np.mean(sales_data[:, 1:], axis=0)
print("Average Sales By Each Year: \n", average_sales_year)

# Average sales per restaurant
average_sales_restaurants = np.mean(sales_data[:, 1:], axis=1)
print("Average Sales per restaurants: \n", average_sales_restaurants)

[     15  810000  945000 1085000 1240000]
Yearly Total: 
 [ 810000  945000 1085000 1240000]
Min Sales Per Restaurents:  [150000 120000 200000 180000 160000]
Max Sales By each Year:
 [200000 230000 260000 300000]
Average Sales By Each Year: 
 [162000. 189000. 217000. 248000.]
Average Sales per restaurants: 
 [200000. 152500. 247500. 225000. 195000.]
